# fzf
brew "fzf"
# git
brew "git"
# chezmoi
brew "chezmoi"
# starship
brew "starship"
# zsh-auto-suggestions
brew "zsh-autosuggestions"
# zsh-syntax-highlighting
brew "zsh-syntax-highlighting"
brew "gum"
